declare module "@/lib/utils"
declare module "@/components/ui/tabs"
declare module "@/components/ui/card"
declare module "@/components/ui/input"
declare module "@/components/ui/label"
declare module "@/components/ui/button"
declare module "@/components/ui/dialog"